In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv("Crop_recommendation.csv")
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["label"]= le.fit_transform(df["label"]) 
df["label"].value_counts()
list(le.classes_)
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=31)
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train,y_train)

/Users/rishabh/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [6]:
clf.score(x_test,y_test)

0.9477272727272728

In [7]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_test,y_test)

0.9840909090909091

In [8]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=25)
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)


0.9954545454545455

In [9]:
y_test

array([12, 18, 16,  6, 14,  4, 18, 11, 21, 12,  0,  3, 19,  5, 17,  7,  0,
        4, 17, 20,  8,  7, 10,  6, 11,  4, 19, 12, 21,  8,  4,  9,  1,  4,
       20, 19,  2,  2, 19, 20, 20, 10, 17, 19,  9, 14,  3, 21, 10,  4, 12,
        0,  7,  2, 11, 15, 14, 15, 15, 19,  9, 10, 20,  4, 18, 20,  7,  4,
        5, 11,  8, 18, 12, 20, 20, 15, 20,  8,  6,  1,  4, 13,  6, 16, 14,
        0, 17, 17,  8,  4,  2, 16, 20, 15,  3, 14,  7, 14,  5,  8, 12,  0,
        1,  6,  6, 20,  6, 21, 13,  9, 15, 10, 21,  0, 21,  6, 15,  0, 15,
        8, 12, 11,  2, 17, 20,  5,  0,  5, 10,  9, 10,  6,  7, 13, 12,  0,
        3,  6,  1, 19, 21,  3,  5, 17, 15,  1, 21,  4, 15,  3,  0,  8, 10,
       18,  6, 12,  6, 19, 19, 11,  2,  5, 17, 17,  3, 18, 14,  0,  3, 21,
       21,  8,  8, 17,  2,  3, 21,  1,  9,  9, 10,  4, 15,  4, 11,  9, 18,
        5,  5,  3, 14,  1, 19, 21,  8,  1,  4, 11, 10, 21,  3,  8, 14, 13,
       17, 21,  8, 20,  8, 21, 15,  1, 12,  6,  0, 21,  9, 21,  0, 10, 11,
        5,  0,  7,  3, 15

In [10]:
rfc.predict([[90,42,43,20,82,6.5,202]])

array([20])

In [11]:
import pickle

In [12]:
pickle.dump(rfc,open("crop_recommendation","wb"))

In [13]:
model=pickle.load(open("crop_recommendation","rb"))

In [14]:
model.predict([[90,42,43,20,82,6.5,202]])

array([20])